CREATE TABLE IF NOT EXISTS %s.jordstykke
(
  gid serial,
  uuid character varying(255),
  featureid double precision,
  featurecode smallint,
  featuretype character varying(40),
  ejerlavsnavn character varying(39),
  landsejerlavskode double precision,
  matrikelnummer character varying(8),
  kms_sagsid double precision,
  kms_journalnummer character varying(12),
  skelforretningssagsid double precision,
  supmsagsid double precision,
  kommunenavn character varying(32),
  kommunekode integer,
  sognenavn character varying(32),
  sognekode integer,
  regionsnavn character varying(32),
  regionskode integer,
  retskredsnavn character varying(32),
  retskredskode integer,
  moderjordstykke double precision,
  registreretareal double precision,
  arealberegn character varying(2),
  vejareal double precision,
  vejarealberegn character varying(8),
  vandarealberegn character varying(6),
  faelleslod character varying(3),
  esr_ejendomsnummer double precision,
  sfe_ejendomsnummer numeric,
  sfe_sagsid double precision,
  sfe_registreringsdato date,
  sfe_journalnummer character varying(15),
  sfe_registrering character varying(15),
  l_noteringstype character varying(22),
  arealtype character varying(20),
  dq_index double precision,
  registreringsdato date,
  geometridato date,
  timeofcreation date,
  the_geom geometry(polygon,25832),
  CONSTRAINT jordstykke_pkey PRIMARY KEY (gid)
)